### Упражнения ДЗ 1
**Задание 1**. Создайте двумерный массив по  12 элементов с помощью `np.arange()` и `np.reshape()`. Выведите основные атрибуты массива.


In [24]:
import numpy as np
a=np.arange(12*2)
a=a.reshape(2,12)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)


[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
2
(2, 12)
24


**Задание 2**. Выведите последний элемент первой строки, а затем третий по счету столбец.


In [25]:
print(a[0,-1])
print(a[:,2])


11
[ 2 14]


**Задание 3**. Найдите средние значения вдоль последней оси массива.

Подсказка: используйте метод `.mean()`


In [26]:
a.mean(axis=-1)


array([ 5.5, 17.5])

**Задание 4**. Замените первые два элемента второй строки и весь последний столбец на значение 1.


In [27]:
a[1,(0,1)]=1
a[:,-1]=1
print(a)


[[ 0  1  2  3  4  5  6  7  8  9 10  1]
 [ 1  1 14 15 16 17 18 19 20 21 22  1]]


**Задание 5**. Отсортируйте первую строку массива от большего к меньшему значению.


In [28]:
a=np.sort(a[0])[::-1]
print(a)


[10  9  8  7  6  5  4  3  2  1  1  0]


**Задание 6**. Преобразуйте массив в квадратную матрицу 4 x 4.


In [29]:
a=np.resize(a,(4,4))
print(a)


[[10  9  8  7]
 [ 6  5  4  3]
 [ 2  1  1  0]
 [10  9  8  7]]


**Задание 7**. Используйте Boolean mask или masked array и опустите значения, которые больше шести.


In [30]:
print(a[a<=6])
a[a>6]=0
print(a)


[6 5 4 3 2 1 1 0]
[[0 0 0 0]
 [6 5 4 3]
 [2 1 1 0]
 [0 0 0 0]]


### Упражнения ДЗ 2
**Задание 1**. Возьмите массив ниже и разделите его на два без остатка.

Подсказка: используйте оператор целочисленного деления.


In [31]:

arr = np.array([[12.5, 8.3, 22.5],
                [13, 17, 20]])
arr // 2


array([[ 6.,  4., 11.],
       [ 6.,  8., 10.]])

**Задание 2**. Ниже даны два массива. Сравните их поэлементно, а также в целом проверьте одинаковые это массивы или нет.

Подсказка: для второй части задания используйте функцию `np.array_equal()`.


In [32]:
c = np.array([3, 4, 4])
d = np.array([3, 4, 5])
print(c==d)
np.array_equal(c,d)


[ True  True False]


False

**Задание 3**. Используя исключающее ИЛИ (`np.logical_xor()`), оцените выражение, при котором элемент массива **c** больше или равен трем, а элемент массива **d** больше или равен четырем. Проверьте полученный результат по таблице истинности.


In [33]:
np.logical_xor(c>=3,d>=4)


array([ True, False, False])

**Задание 4**. Представим, что в массиве ниже записаны оценки, полученные на экзамене. С помощью функции `np.where()` создайте новый массив, в котором будет записано "Зачет", если соответствующее значение в исходном массиве больше либо равно трем, в противном случае должно быть записано "Незачет".

Подсказка: слова "Зачет" и "Незачет" не обязательно преобразовывать в списки той же длины, что и список с оценками, можно просто вписать их вторыи и третьим параметрами в функцию `np.where()`.


In [34]:
scores = np.array([3, 2, 4, 5, 5, 2])
np.where(scores>=3,"Зачет","Незачет")


array(['Зачет', 'Незачет', 'Зачет', 'Зачет', 'Зачет', 'Незачет'],
      dtype='<U7')

**Задание 5**. Ниже приведены матрица 4 x 3 и вектор 3 x 1. Какой вектор или матрицу (объект какой размерности) мы получим при их скалярном произведении? Напишите программу вычисления результата.


In [35]:
A = np.array([[2, 3, 4],
              [3, 2, 1],
              [9, 4, 2],
              [2, 3, 1]])

x = np.array([[2],
              [2],
              [1]])
res = np.dot(A,x)
print(res,"\n", res.shape)


[[14]
 [11]
 [28]
 [11]] 
 (4, 1)


**Задание 6**. Даны две матрицы C и D. (1) Возможно ли скалярное умножение матрицы C на D? Если нет, объясните почему. (2) Что можно сделать, чтобы умножение C на D стало возможным?

Подсказка: в матрице D превратите строки в столбцы.


In [36]:
C = np.array([[1, 2, 3],
    [1, 2, 3]])

D = np.array([[2, 3, 4],
    [3, 2, 1]])

#(1)Размертность строк в C не равно размерности столбцов в D, (2) Транспонировать D
np.dot(C,D.T)


array([[20, 10],
       [20, 10]])

**Задание 7**. Возьмите матрицы из предыдущего упражнения. Умножьте эти матрицы вдоль первой оси каждой из них (axes = (1, 1)), используя функцию `np.tensordot()`. Объясните, почему вы получили тот же результат, что и во второй части предыдущего упражнения.


In [37]:
np.tensordot(C,D,axes=(1,1))
#Скалярное произведение - произведение вокруг последней оси 1-й матрицы и предпоследней оси второй, при транспонировании оси меняются местами.


array([[20, 10],
       [20, 10]])

**Задание 8**. Продолжаем работать с матрицами C и D. Получите тот же результат скалярного произведения, что и в двух предыдущих заданиях, но на этот раз используя функцию `np.einsum()`.

Подсказка: обозначьте оси матриц C и D буквами i, j и k; умножение будет происходить вдоль той оси, буквенное обозначение которой повторяется в обеих частях условия первого параметра функции `np.einsum()`.


In [38]:
np.einsum('ij,kj -> ik',C,D)


array([[20, 10],
       [20, 10]])

**Задание 9**. (1) Создайте нулевую матрицу размером 4 x 4. (2) Заполните ее главную диагональ единицами. (3) Теперь создайте единичную матрицу такого же размера и проверьте равны ли получившиеся матрицы с помощью функции `np.array_equal()`.


In [39]:
a=np.zeros((4,4))
np.fill_diagonal(a,1)
b=np.eye(4)
np.array_equal(a,b)


True

**Задание 10**. Ниже дана система линейных уравнений $AX = B$. Решите ее с помощью Питона, зная что $X = A^{-1}B$.
$$
\left\{
    \begin{matrix}
    4x  + 3y = 20 \\
    -5x + 9y = 26
    \end{matrix}
\right.
$$


In [40]:
A = np.array([[4, 3],
    [-5, 9]])

B = np.array([[20],
    [26]])

X=np.linalg.inv(A).dot(B)
X

array([[2.],
       [4.]])